version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5555:5555"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookstore
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
